# Generated by Django 5.2.5 on 2025-09-07 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FootballItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the football item', max_length=255)),
                ('price', models.IntegerField(help_text='Price in rupiah')),
                ('description', models.TextField(help_text='Detailed description of the item')),
                ('thumbnail', models.URLField(help_text='URL to item image', max_length=500)),
                ('category', models.CharField(help_text='Item category (e.g., Jersey, Boots, Ball)', max_length=100)),
                ('is_featured', models.BooleanField(default=False, help_text='Whether this item is featured')),
                ('brand', models.CharField(blank=True, help_text='Brand name (e.g., Nike, Adidas)', max_length=100, null=True)),
                ('stock', models.IntegerField(default=0, help_text='Number of items in stock')),
                ('size', models.CharField(blank=True, help_text='Size (S, M, L, XL, or shoe sizes)', max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
