# Generated by Django 5.2.6 on 2025-09-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_footballitem_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Name of the car', max_length=255)),
                ('brand', models.CharField(help_text='Brand of the car (e.g., Toyota, Honda, BMW)', max_length=255)),
                ('stock', models.IntegerField(default=0, help_text='Number of cars in stock')),
            ],
        ),
    ]
